import Mock from "mockjs";

let List=[]
export default {
    getStatisticalData:()=>{
        for(let i=0;i<7;i++){
            List.push(
                Mock.mock({
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    oppo:Mock.Random.float(100,8000,0,0),
                    samsung:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0),
                    华为:Mock.Random.float(100,8000,0,0),
                })
            )
        }
        return {
            code:20000,
            data:{
                videoData:[
                    {
                        name:'苹果',
                        value:2999
                    },
                    {
                        name:'vivo',
                        value:2999
                    },
                    {
                        name:'oppo',
                        value:2999
                    },
                    {
                        name:'samsung',
                        value:2999
                    },
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'华为',
                        value:2999
                    },

                ],
                userData:[
                    {
                        date:'周一',
                        new:5,
                        active:200
                    },
                    {
                        date:'周二',
                        new:10,
                        active:500
                    },
                    {
                        date:'周三',
                        new:12,
                        active:550
                    },
                    {
                        date:'周四',
                        new:5,
                        active:200
                    },{
                        date:'周五',
                        new:5,
                        active:200
                    },
                    {
                        date:'周六',
                        new:5,
                        active:200
                    },
                    {
                        date:'周七',
                        new:5,
                        active:200
                    },

                ],
                orderData:
                    {
                        date:['20191001','20191002','20191003','20191004','20191005','20191006','20191007',],
                        data:List
                    },
                tableData:[
                    {
                        name:'oppo',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'vivo',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'苹果',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'samsung',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },{
                        name:'华为',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },{
                        name:'小米',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                ],

            }
        }
    }

}
